language: python

python:
  - "3.6"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

  # Useful for debugging any issues with conda
  - conda info -a

  # set up a conda environment with the right Python version.
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test

  # Below, include the dependencies you want to install with conda, optionally
  # specifying versions used in the matrix above. If you split this into
  # multiple conda install commands, you should always include numpy=$NUMPY as
  # the first package to install (for every conda install command) otherwise
  # numpy may be automatically upgraded.

  - conda install --yes numpy scipy matplotlib pytest pip pyomo
  - conda install -c conda-forge pyomo

  # You can also install some dependencies with pip if not available in conda
  # - pip install ...


script: python test_urbs